version: '3'

services:
  worker:
    restart: on-failure
    build: .
    environment:
        PGHOST: "db"
        PGPORT: "5432"
        PGUSER: "postgres"
        PGPASSWORD: ""
        PGDATABASE: "postgres"
        PGSSLMODE: "disable"
  db:
    image: "postgres:latest"
    ports: 
      - "5432:5432"

